// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/home/About.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Feedbacks: typeof import('./components/home/feedbacks.vue')['default']
    FlashMessage: typeof import('./components/flashMessage.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceFour: typeof import('./components/home/serviceFour.vue')['default']
    SilderHome: typeof import('./components/silderHome.vue')['default']
    Topbar: typeof import('./components/topbar.vue')['default']
  }
}
